# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('enderecop', models.CharField(max_length=100)),
                ('cidadep', models.CharField(max_length=100)),
                ('estadop', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Par\xe1'), ('PB', 'Paraiba'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cepp', models.CharField(max_length=9)),
                ('telefonep', models.CharField(max_length=11)),
                ('celularp', models.CharField(max_length=11)),
                ('skypep', models.CharField(max_length=20)),
                ('BPWassociada', models.CharField(choices=[(1, 'S\xe3o Paulo'), (2, 'Florianopolis')], max_length=2)),
                ('tipo', models.CharField(choices=[('L', 'Profisssional Liberal'), ('J', 'Pessoa Juridica')], max_length=1)),
                ('razaosocial', models.CharField(max_length=100)),
                ('nomefantasia', models.CharField(max_length=100)),
                ('enderecoe', models.CharField(max_length=100)),
                ('cidadee', models.CharField(max_length=100)),
                ('estadoe', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Par\xe1'), ('PB', 'Paraiba'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cepe', models.CharField(max_length=9)),
                ('telefonee', models.CharField(max_length=11)),
                ('emaile', models.EmailField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('dtfundacao', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('cotas', models.CharField(max_length=2)),
                ('funcionarios', models.PositiveIntegerField(max_length=2)),
                ('exportatempo', models.PositiveIntegerField(max_length=3)),
                ('principalpais', models.CharField(max_length=100)),
                ('liberainfs', models.BooleanField(max_length=100)),
                ('segmentotemp', models.CharField(max_length=100)),
                ('certificacaotemp', models.CharField(max_length=100)),
            ],
        ),
    ]
